/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['activate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['admin_login'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/redirect': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['admin_redirect'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['logout_all'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/password/change': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['password_change'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['password_reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/password/reset/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['password_reset_confirm'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActivateRequest: {
      password: string;
      /** @description 不透明な有効化トークン `"{id}.{secret}"`。 */
      token: string;
    };
    AdminRedirectRequest: {
      code: string;
      state: string;
    };
    AdminTokenResponse: {
      access_token: string;
      refresh_token: string;
    };
    ChangePasswordRequest: {
      new_password: string;
      old_password: string;
    };
    LoginRequest: {
      m_address: string;
      password: string;
    };
    PasswordResetConfirmRequest: {
      new_password: string;
      /** @description 不透明なリセットトークン `"{id}.{secret}"`。 */
      token: string;
    };
    PasswordResetRequest: {
      m_address: string;
    };
    /**
     * @description ログイン/リフレッシュ成功時のレスポンス。リフレッシュトークンは本文に含めず
     *     `__Host-` Cookie で配送する。アクセストークンのみ本文で返す。
     */
    TokenResponse: {
      access_token: string;
      /**
       * Format: int64
       * @description アクセストークンの有効秒数。
       */
      expires_in: number;
      token_type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  activate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivateRequest'];
      };
    };
    responses: {
      /** @description 有効化成功(初回パスワード設定) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description パスワードポリシー違反 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description トークン無効/失効/消費済み */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 既に有効化済み */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Keycloak 認可エンドポイントへリダイレクト */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_redirect: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminRedirectRequest'];
      };
    };
    responses: {
      /** @description Keycloak トークン */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminTokenResponse'];
        };
      };
      /** @description 未知の state */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description ログイン成功。リフレッシュトークンは Set-Cookie で配送 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description 認証失敗(存在/状態を区別しない汎用) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ログアウト(冪等)。Cookie をクリア */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout_all: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 全デバイスのセッションを失効。Cookie クリア */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description アクセストークン無効 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_change: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description 変更成功。全セッション失効・Cookie クリア */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 新パスワードがポリシー違反 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description アクセストークン無効 / 旧パスワード不一致 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description 常に 202(存在/不在を漏らさない) */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_confirm: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirmRequest'];
      };
    };
    responses: {
      /** @description リセット成功。全セッション失効・Cookie クリア */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description パスワードポリシー違反 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description トークン無効/失効/消費済み */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 回転成功。新リフレッシュトークンを Set-Cookie */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description トークン無効 / reuse 検知 / Cookie 無し */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
