/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 場所の検索
     * @description 企画実施場所の一覧を階層IDつきのフラットな形式で返します。type(完全一致)・name(完全一致)・displayName(部分一致)で絞り込みできます。
     */
    get: operations['listPlaces'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/places/{placeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 場所の取得
     * @description 階層IDで指定した場所を1件返します。
     */
    get: operations['getPlace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 企画の一覧
     * @description 登録されている企画をすべて返します。
     */
    get: operations['listProjects'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/projects/{projectId}/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 企画詳細情報の取得
     * @description IDで指定した企画の詳細情報を返します。
     */
    get: operations['getProjectDetails'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 企画の取得
     * @description IDで指定した企画を1件返します。
     */
    get: operations['getProject'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/projects/{projectId}/icon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 企画アイコンの取得
     * @description IDで指定した企画のアイコン原本を返します。
     */
    get: operations['getProjectIcon'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 企画の登録
     * @description 企画を新規登録します。ID は呼び出し側が指定します。
     */
    post: operations['createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 企画の一括登録
     * @description 企画をまとめて新規登録します。ID は呼び出し側が指定します。一件でも登録できなければ、一件も登録されません。一度に登録できるのは 100 件までです。
     */
    post: operations['createProjects'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 企画の更新
     * @description 企画を丸ごと置き換えます。タグと開催予定は差分ではなく総入れ替えになります。
     */
    put: operations['updateProject'];
    post?: never;
    /**
     * 企画の削除
     * @description 企画を削除します。タグと開催予定も一緒に消えます。
     */
    delete: operations['deleteProject'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects/{projectId}/description': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 企画説明の更新
     * @description 企画の説明だけを書き換えます。他の項目・タグ・開催予定は変わりません。
     */
    patch: operations['updateProjectDescription'];
    trace?: never;
  };
  '/admin/v1/projects/{projectId}/icon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 企画アイコンの更新
     * @description Cloudflare Imagesで扱える正方形の画像を、企画アイコンの原本として保存します。
     */
    put: operations['updateProjectIcon'];
    post?: never;
    /**
     * 企画アイコンの削除
     * @description 企画アイコンの原本を削除します。未登録の場合も成功します。
     */
    delete: operations['deleteProjectIcon'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects/{projectId}/details/menu': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 企画メニューの登録・更新
     * @description 指定した企画のメニューを保存します。追加情報は変更しません。
     */
    put: operations['updateProjectMenu'];
    post?: never;
    /**
     * 企画メニューの削除
     * @description 指定した企画のメニューを削除します。追加情報は変更しません。
     */
    delete: operations['deleteProjectMenu'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/v1/projects/{projectId}/details/additionalInfo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 企画追加情報の登録・更新
     * @description 指定した企画の追加情報を保存します。メニューは変更しません。
     */
    put: operations['updateProjectAdditionalInfo'];
    post?: never;
    /**
     * 企画追加情報の削除
     * @description 指定した企画の追加情報を削除します。メニューは変更しません。
     */
    delete: operations['deleteProjectAdditionalInfo'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Room: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'room';
      floor: string;
      alias?: string;
    };
    Building: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'building';
      rooms: components['schemas']['Room'][];
    };
    Stage: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'stage';
    };
    Outdoor: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'outdoor';
    };
    FoodStallSlot: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'food_stall_slot';
    };
    FoodStallArea: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'food_stall_area';
      slots: components['schemas']['FoodStallSlot'][];
    };
    Venue:
      | components['schemas']['Building']
      | components['schemas']['Stage']
      | components['schemas']['Outdoor']
      | components['schemas']['FoodStallArea'];
    District: {
      name: string;
      displayName: string;
      /** @enum {string} */
      type: 'district';
      venues: components['schemas']['Venue'][];
    };
    Place:
      | components['schemas']['District']
      | components['schemas']['Venue']
      | components['schemas']['Room']
      | components['schemas']['FoodStallSlot'];
    /** @enum {string} */
    Category:
      | 'hearty'
      | 'street_food'
      | 'sweets'
      | 'performance'
      | 'play'
      | 'cafe'
      | 'laboratory'
      | 'display';
    Time: {
      /** @enum {number} */
      date: 1 | 2;
      hour: number;
      minute: number;
    };
    TimeRange: {
      start: components['schemas']['Time'];
      end: components['schemas']['Time'];
    };
    Occasion: {
      /** @enum {string} */
      place?:
        | 'east'
        | 'east.taki-plaza'
        | 'east.taki-plaza.tp-b1-event'
        | 'east.taki-plaza.tp-b2-event'
        | 'east.taki-plaza.tp-1'
        | 'east.centennial-hall'
        | 'east.centennial-hall.centennial-hall-1f'
        | 'east.taki-plaza-stage'
        | 'east.wood-deck-stage'
        | 'east.wood-deck'
        | 'east.outdoor-stage'
        | 'east.fs-east-icho'
        | 'east.fs-east-icho.1'
        | 'east.fs-east-icho.2'
        | 'east.fs-east-icho.3'
        | 'east.fs-east-icho.4'
        | 'east.fs-east-icho.5'
        | 'east.fs-east-icho.6'
        | 'east.fs-east-icho.7'
        | 'east.fs-east-icho.8'
        | 'east.fs-east-icho.9'
        | 'east.fs-east-icho.10'
        | 'east.fs-behind-taki-plaza'
        | 'east.fs-behind-taki-plaza.1'
        | 'east.fs-behind-taki-plaza.2'
        | 'east.fs-behind-taki-plaza.3'
        | 'east.fs-behind-taki-plaza.4'
        | 'east.fs-behind-taki-plaza.5'
        | 'east.fs-behind-taki-plaza.6'
        | 'east.fs-east-deck'
        | 'east.fs-east-deck.1'
        | 'east.fs-east-deck.2'
        | 'east.fs-east-deck.3'
        | 'east.fs-east-deck.4'
        | 'east.fs-east-deck.5'
        | 'east.fs-east-deck.6'
        | 'east.fs-east-deck.7'
        | 'east.fs-east-deck.8'
        | 'east.fs-east-deck.9'
        | 'east.fs-east-deck.10'
        | 'east.fs-east-deck.11'
        | 'main'
        | 'main.m'
        | 'main.m.m-b07'
        | 'main.m.m-b45'
        | 'main.m.m-b43'
        | 'main.m.m-101'
        | 'main.m.m-102'
        | 'main.m.m-107'
        | 'main.m.m-112'
        | 'main.m.m-119'
        | 'main.m.m-123'
        | 'main.m.m-134'
        | 'main.m.m-135'
        | 'main.m.m-143a'
        | 'main.m.m-143b'
        | 'main.m.m-155'
        | 'main.m.m-156'
        | 'main.m.m-157'
        | 'main.m.m-178'
        | 'main.m.m-278'
        | 'main.m.m-356'
        | 'main.m.m-b61'
        | 'main.m.m-213'
        | 'main.m.m-290'
        | 'main.m.m-124'
        | 'main.m.m-220'
        | 'main.m.m-225'
        | 'main.m.m-374'
        | 'main.mb'
        | 'main.mb.m-b101'
        | 'main.mb.m-b104'
        | 'main.mb.m-b107'
        | 'main.fs-honkan-main'
        | 'main.fs-honkan-main.1'
        | 'main.fs-honkan-main.2'
        | 'main.fs-honkan-main.3'
        | 'main.fs-honkan-main.4'
        | 'main.fs-honkan-main.5'
        | 'main.fs-honkan-main.6'
        | 'main.fs-honkan-main.7'
        | 'main.fs-honkan-main.8'
        | 'main.fs-honkan-main.9'
        | 'main.fs-honkan-main.10'
        | 'main.fs-honkan-main.11'
        | 'main.fs-honkan-main.12'
        | 'main.fs-honkan-main.13'
        | 'main.fs-honkan-main.14'
        | 'main.fs-honkan-west'
        | 'main.fs-honkan-west.1'
        | 'main.fs-honkan-west.2'
        | 'south'
        | 'south.s1'
        | 'south.s1.s1-101'
        | 'south.s2'
        | 'south.s2.s2-201'
        | 'south.s2.s2-202'
        | 'south.s2.s2-203'
        | 'south.s2.s2-204'
        | 'south.s2.s2-101'
        | 'south.s2.s2-109'
        | 'south.s2.mono'
        | 'south.s3'
        | 'south.s3.s3-206'
        | 'south.s3.s3-207'
        | 'south.s3.s3-215'
        | 'south.s3.s3-300'
        | 'south.s3.s3-310'
        | 'south.s3.s3-403'
        | 'south.s3.s3-413'
        | 'south.s3.s3-414'
        | 'south.s3.s3-505'
        | 'south.s3.s3-510'
        | 'south.s3.s3-601'
        | 'south.s3.s3-611'
        | 'south.s3.s3-906'
        | 'south.s3.s3-914'
        | 'south.s4'
        | 'south.s4.s4-201'
        | 'south.s4.s4-202'
        | 'south.s4.s4-203'
        | 'south.s7'
        | 'south.s7.s7-201'
        | 'south.s7.s7-202'
        | 'south.s7.s7-207'
        | 'south.s7.s7-512'
        | 'south.s7.s7-605'
        | 'south.s7.s7-701'
        | 'south.s7.s7-702'
        | 'south.s7.s7-703'
        | 'south.s7.s7-707'
        | 'south.s7.s7-804'
        | 'south.s7.s7-807'
        | 'south.s8'
        | 'south.s8.s8-101'
        | 'south.s8.s8-107'
        | 'south.s8.s8-501'
        | 'south.s8.s8-512'
        | 'south.s8.s8-516'
        | 'south.s8.s8-518'
        | 'south.s8.s8-520'
        | 'south.s8.s8-entrance'
        | 'south.sl'
        | 'south.sl.sl-101'
        | 'south.circle-1'
        | 'south.circle-1.c1-212'
        | 'south.lab2'
        | 'south.lab2.lab2-storage'
        | 'south.waste-station'
        | 'south.seven-front'
        | 'south.fs-south-east'
        | 'south.fs-south-east.1'
        | 'south.fs-south-east.2'
        | 'south.fs-south-east.3'
        | 'south.fs-south-east.4'
        | 'south.fs-south-east.5'
        | 'south.fs-south-east.6'
        | 'south.fs-south-east.7'
        | 'south.fs-south-east.8'
        | 'south.fs-south-east.9'
        | 'south.fs-south-east.10'
        | 'south.fs-south-east.11'
        | 'south.fs-south-east.12'
        | 'south.fs-south-east.13'
        | 'south.fs-south-east.14'
        | 'south.fs-south-east.15'
        | 'south.fs-south-east.16'
        | 'south.fs-south-east.17'
        | 'south.fs-south-east.18'
        | 'south.fs-south-east.19'
        | 'south.fs-south-east.20'
        | 'south.fs-south-east.21'
        | 'south.fs-south-east.22'
        | 'south.fs-south-east.23'
        | 'south.fs-south-east.24'
        | 'south.fs-south-west'
        | 'south.fs-south-west.1'
        | 'south.fs-south-west.2'
        | 'south.fs-south-west.3'
        | 'south.fs-south-west.4'
        | 'south.fs-south-west.5'
        | 'south.fs-south-west.6'
        | 'south.fs-south-west.7'
        | 'south.fs-south-west.8'
        | 'south.fs-south-west.9'
        | 'south.fs-south-west.10'
        | 'south.fs-south-west.11'
        | 'south.fs-south-west.12'
        | 'south.fs-south-west.13'
        | 'south.fs-south-west.14'
        | 'south.fs-south-west.15'
        | 'south.fs-south-west.16'
        | 'west'
        | 'west.w2'
        | 'west.w2.w2-401'
        | 'west.w2.w2-402'
        | 'west.w3'
        | 'west.w3.w3-201'
        | 'west.w3.w3-205'
        | 'west.w3.w3-207'
        | 'west.w3.w3-301'
        | 'west.w3.w3-305'
        | 'west.w3.w3-501'
        | 'west.w3.w3-707'
        | 'west.w3.w3-505'
        | 'west.w5'
        | 'west.w5.w5-104'
        | 'west.w5.w5-105'
        | 'west.w5.w5-106'
        | 'west.w5.w5-107'
        | 'west.w5.tsubame'
        | 'west.w8'
        | 'west.w8.w8-404'
        | 'west.w8.w8-407'
        | 'west.w8.w8-509'
        | 'west.w8.w8-601'
        | 'west.w8.w8-604'
        | 'west.w8.w8-609'
        | 'west.w8.w8-7rf'
        | 'west.w8.w8-901'
        | 'west.w8.w8-5ev'
        | 'west.w9'
        | 'west.w9.w9-201'
        | 'west.w9.w9-202'
        | 'west.w9.w9-321'
        | 'west.w9.w9-322'
        | 'west.w9.w9-323'
        | 'west.w9.w9-324'
        | 'west.w9.w9-325'
        | 'west.w9.w9-326'
        | 'west.w9.w9-327'
        | 'west.w9.w9-606a'
        | 'west.w9.w9-706'
        | 'west.w9.w9-707'
        | 'west.w9.w9-716'
        | 'west.w9.w9-733'
        | 'west.wl1'
        | 'west.wl1.wl1-201'
        | 'west.wl1.wl1-401'
        | 'west.wl2'
        | 'west.wl2.wl2-101'
        | 'west.wl2.wl2-201'
        | 'west.wl2.wl2-301'
        | 'west.wl2.wl2-401'
        | 'west.lecture-hall-70'
        | 'west.digital-hall'
        | 'west.gym'
        | 'west.gym.gym-arena'
        | 'west.gym.gym-dojo'
        | 'west.circle-2'
        | 'west.circle-2.c2-102'
        | 'west.circle-2.c2-201'
        | 'north'
        | 'north.n1'
        | 'north.n1.n1-158'
        | 'north.n1.n1-parking'
        | 'north.n3'
        | 'north.n3.n3-lab'
        | 'north.lab1'
        | 'north.lab1.lab1-1f'
        | 'midorigaoka'
        | 'midorigaoka.mi6'
        | 'midorigaoka.mi6.mi6-302'
        | 'midorigaoka.mi6.mi6-303'
        | 'ishikawadai'
        | 'ishikawadai.i1'
        | 'ishikawadai.i1.i1-254'
        | 'ishikawadai.i1.i1-255'
        | 'ishikawadai.i1.i1-256'
        | 'ishikawadai.i1.i1-751'
        | 'ishikawadai.i7'
        | 'ishikawadai.i7.i7-mishima'
        | 'ishikawadai.i9'
        | 'ishikawadai.i9.i9-207'
        | 'ishikawadai.fs-ishikawadai'
        | 'ishikawadai.fs-ishikawadai.1'
        | 'ishikawadai.fs-ishikawadai.2'
        | 'ishikawadai.fs-ishikawadai.3'
        | 'ishikawadai.fs-ishikawadai.4'
        | 'ishikawadai.fs-ishikawadai.5'
        | 'ishikawadai.fs-ishikawadai.6'
        | 'ishikawadai.fs-ishikawadai.7';
      timeRange: components['schemas']['TimeRange'];
    };
    MainFoodStallTag: {
      /** @enum {string} */
      tag: 'main';
      /** @enum {string} */
      tag2:
        | 'rice'
        | 'noodle_flour'
        | 'skewer_grill'
        | 'snack'
        | 'soup'
        | 'world';
    };
    SweetFoodStallTag: {
      /** @enum {string} */
      tag: 'sweet';
      /** @enum {string} */
      tag2: 'japanese' | 'western' | 'cold' | 'snack' | 'drink' | 'world';
    };
    DrinkFoodStallTag: {
      /** @enum {string} */
      tag: 'drink';
    };
    FoodStallTag:
      | components['schemas']['MainFoodStallTag']
      | components['schemas']['SweetFoodStallTag']
      | components['schemas']['DrinkFoodStallTag'];
    FoodStallProject: {
      id: string;
      groupName: string;
      projectName: string;
      description: string;
      isChildFriendly: boolean;
      isRecommended: boolean;
      category?: components['schemas']['Category'];
      occasions: components['schemas']['Occasion'][];
      /** @enum {string} */
      type: 'food-stall';
      tag: components['schemas']['FoodStallTag'][];
      offering?: string;
    };
    /** @enum {string} */
    GeneralTag: 'experience' | 'display' | 'performance' | 'food' | 'lecture';
    GeneralProject: {
      id: string;
      groupName: string;
      projectName: string;
      description: string;
      isChildFriendly: boolean;
      isRecommended: boolean;
      category?: components['schemas']['Category'];
      occasions: components['schemas']['Occasion'][];
      /** @enum {string} */
      type: 'general';
      tag: components['schemas']['GeneralTag'][];
    };
    LaboratoryProject: {
      id: string;
      groupName: string;
      projectName: string;
      description: string;
      isChildFriendly: boolean;
      isRecommended: boolean;
      category?: components['schemas']['Category'];
      occasions: components['schemas']['Occasion'][];
      /** @enum {string} */
      type: 'laboratory';
      isTour: boolean;
    };
    StageProject: {
      id: string;
      groupName: string;
      projectName: string;
      description: string;
      isChildFriendly: boolean;
      isRecommended: boolean;
      category?: components['schemas']['Category'];
      occasions: components['schemas']['Occasion'][];
      /** @enum {string} */
      type: 'stage';
    };
    Project:
      | components['schemas']['FoodStallProject']
      | components['schemas']['GeneralProject']
      | components['schemas']['LaboratoryProject']
      | components['schemas']['StageProject'];
    ProjectList: components['schemas']['Project'][];
    ProjectDescription: {
      description: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPlaces: {
    parameters: {
      query?: {
        type?:
          | 'district'
          | 'building'
          | 'stage'
          | 'outdoor'
          | 'food_stall_area'
          | 'room'
          | 'food_stall_slot';
        name?: string;
        displayName?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 条件に一致した場所の一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            id:
              | 'east'
              | 'east.taki-plaza'
              | 'east.taki-plaza.tp-b1-event'
              | 'east.taki-plaza.tp-b2-event'
              | 'east.taki-plaza.tp-1'
              | 'east.centennial-hall'
              | 'east.centennial-hall.centennial-hall-1f'
              | 'east.taki-plaza-stage'
              | 'east.wood-deck-stage'
              | 'east.wood-deck'
              | 'east.outdoor-stage'
              | 'east.fs-east-icho'
              | 'east.fs-east-icho.1'
              | 'east.fs-east-icho.2'
              | 'east.fs-east-icho.3'
              | 'east.fs-east-icho.4'
              | 'east.fs-east-icho.5'
              | 'east.fs-east-icho.6'
              | 'east.fs-east-icho.7'
              | 'east.fs-east-icho.8'
              | 'east.fs-east-icho.9'
              | 'east.fs-east-icho.10'
              | 'east.fs-behind-taki-plaza'
              | 'east.fs-behind-taki-plaza.1'
              | 'east.fs-behind-taki-plaza.2'
              | 'east.fs-behind-taki-plaza.3'
              | 'east.fs-behind-taki-plaza.4'
              | 'east.fs-behind-taki-plaza.5'
              | 'east.fs-behind-taki-plaza.6'
              | 'east.fs-east-deck'
              | 'east.fs-east-deck.1'
              | 'east.fs-east-deck.2'
              | 'east.fs-east-deck.3'
              | 'east.fs-east-deck.4'
              | 'east.fs-east-deck.5'
              | 'east.fs-east-deck.6'
              | 'east.fs-east-deck.7'
              | 'east.fs-east-deck.8'
              | 'east.fs-east-deck.9'
              | 'east.fs-east-deck.10'
              | 'east.fs-east-deck.11'
              | 'main'
              | 'main.m'
              | 'main.m.m-b07'
              | 'main.m.m-b45'
              | 'main.m.m-b43'
              | 'main.m.m-101'
              | 'main.m.m-102'
              | 'main.m.m-107'
              | 'main.m.m-112'
              | 'main.m.m-119'
              | 'main.m.m-123'
              | 'main.m.m-134'
              | 'main.m.m-135'
              | 'main.m.m-143a'
              | 'main.m.m-143b'
              | 'main.m.m-155'
              | 'main.m.m-156'
              | 'main.m.m-157'
              | 'main.m.m-178'
              | 'main.m.m-278'
              | 'main.m.m-356'
              | 'main.m.m-b61'
              | 'main.m.m-213'
              | 'main.m.m-290'
              | 'main.m.m-124'
              | 'main.m.m-220'
              | 'main.m.m-225'
              | 'main.m.m-374'
              | 'main.mb'
              | 'main.mb.m-b101'
              | 'main.mb.m-b104'
              | 'main.mb.m-b107'
              | 'main.fs-honkan-main'
              | 'main.fs-honkan-main.1'
              | 'main.fs-honkan-main.2'
              | 'main.fs-honkan-main.3'
              | 'main.fs-honkan-main.4'
              | 'main.fs-honkan-main.5'
              | 'main.fs-honkan-main.6'
              | 'main.fs-honkan-main.7'
              | 'main.fs-honkan-main.8'
              | 'main.fs-honkan-main.9'
              | 'main.fs-honkan-main.10'
              | 'main.fs-honkan-main.11'
              | 'main.fs-honkan-main.12'
              | 'main.fs-honkan-main.13'
              | 'main.fs-honkan-main.14'
              | 'main.fs-honkan-west'
              | 'main.fs-honkan-west.1'
              | 'main.fs-honkan-west.2'
              | 'south'
              | 'south.s1'
              | 'south.s1.s1-101'
              | 'south.s2'
              | 'south.s2.s2-201'
              | 'south.s2.s2-202'
              | 'south.s2.s2-203'
              | 'south.s2.s2-204'
              | 'south.s2.s2-101'
              | 'south.s2.s2-109'
              | 'south.s2.mono'
              | 'south.s3'
              | 'south.s3.s3-206'
              | 'south.s3.s3-207'
              | 'south.s3.s3-215'
              | 'south.s3.s3-300'
              | 'south.s3.s3-310'
              | 'south.s3.s3-403'
              | 'south.s3.s3-413'
              | 'south.s3.s3-414'
              | 'south.s3.s3-505'
              | 'south.s3.s3-510'
              | 'south.s3.s3-601'
              | 'south.s3.s3-611'
              | 'south.s3.s3-906'
              | 'south.s3.s3-914'
              | 'south.s4'
              | 'south.s4.s4-201'
              | 'south.s4.s4-202'
              | 'south.s4.s4-203'
              | 'south.s7'
              | 'south.s7.s7-201'
              | 'south.s7.s7-202'
              | 'south.s7.s7-207'
              | 'south.s7.s7-512'
              | 'south.s7.s7-605'
              | 'south.s7.s7-701'
              | 'south.s7.s7-702'
              | 'south.s7.s7-703'
              | 'south.s7.s7-707'
              | 'south.s7.s7-804'
              | 'south.s7.s7-807'
              | 'south.s8'
              | 'south.s8.s8-101'
              | 'south.s8.s8-107'
              | 'south.s8.s8-501'
              | 'south.s8.s8-512'
              | 'south.s8.s8-516'
              | 'south.s8.s8-518'
              | 'south.s8.s8-520'
              | 'south.s8.s8-entrance'
              | 'south.sl'
              | 'south.sl.sl-101'
              | 'south.circle-1'
              | 'south.circle-1.c1-212'
              | 'south.lab2'
              | 'south.lab2.lab2-storage'
              | 'south.waste-station'
              | 'south.seven-front'
              | 'south.fs-south-east'
              | 'south.fs-south-east.1'
              | 'south.fs-south-east.2'
              | 'south.fs-south-east.3'
              | 'south.fs-south-east.4'
              | 'south.fs-south-east.5'
              | 'south.fs-south-east.6'
              | 'south.fs-south-east.7'
              | 'south.fs-south-east.8'
              | 'south.fs-south-east.9'
              | 'south.fs-south-east.10'
              | 'south.fs-south-east.11'
              | 'south.fs-south-east.12'
              | 'south.fs-south-east.13'
              | 'south.fs-south-east.14'
              | 'south.fs-south-east.15'
              | 'south.fs-south-east.16'
              | 'south.fs-south-east.17'
              | 'south.fs-south-east.18'
              | 'south.fs-south-east.19'
              | 'south.fs-south-east.20'
              | 'south.fs-south-east.21'
              | 'south.fs-south-east.22'
              | 'south.fs-south-east.23'
              | 'south.fs-south-east.24'
              | 'south.fs-south-west'
              | 'south.fs-south-west.1'
              | 'south.fs-south-west.2'
              | 'south.fs-south-west.3'
              | 'south.fs-south-west.4'
              | 'south.fs-south-west.5'
              | 'south.fs-south-west.6'
              | 'south.fs-south-west.7'
              | 'south.fs-south-west.8'
              | 'south.fs-south-west.9'
              | 'south.fs-south-west.10'
              | 'south.fs-south-west.11'
              | 'south.fs-south-west.12'
              | 'south.fs-south-west.13'
              | 'south.fs-south-west.14'
              | 'south.fs-south-west.15'
              | 'south.fs-south-west.16'
              | 'west'
              | 'west.w2'
              | 'west.w2.w2-401'
              | 'west.w2.w2-402'
              | 'west.w3'
              | 'west.w3.w3-201'
              | 'west.w3.w3-205'
              | 'west.w3.w3-207'
              | 'west.w3.w3-301'
              | 'west.w3.w3-305'
              | 'west.w3.w3-501'
              | 'west.w3.w3-707'
              | 'west.w3.w3-505'
              | 'west.w5'
              | 'west.w5.w5-104'
              | 'west.w5.w5-105'
              | 'west.w5.w5-106'
              | 'west.w5.w5-107'
              | 'west.w5.tsubame'
              | 'west.w8'
              | 'west.w8.w8-404'
              | 'west.w8.w8-407'
              | 'west.w8.w8-509'
              | 'west.w8.w8-601'
              | 'west.w8.w8-604'
              | 'west.w8.w8-609'
              | 'west.w8.w8-7rf'
              | 'west.w8.w8-901'
              | 'west.w8.w8-5ev'
              | 'west.w9'
              | 'west.w9.w9-201'
              | 'west.w9.w9-202'
              | 'west.w9.w9-321'
              | 'west.w9.w9-322'
              | 'west.w9.w9-323'
              | 'west.w9.w9-324'
              | 'west.w9.w9-325'
              | 'west.w9.w9-326'
              | 'west.w9.w9-327'
              | 'west.w9.w9-606a'
              | 'west.w9.w9-706'
              | 'west.w9.w9-707'
              | 'west.w9.w9-716'
              | 'west.w9.w9-733'
              | 'west.wl1'
              | 'west.wl1.wl1-201'
              | 'west.wl1.wl1-401'
              | 'west.wl2'
              | 'west.wl2.wl2-101'
              | 'west.wl2.wl2-201'
              | 'west.wl2.wl2-301'
              | 'west.wl2.wl2-401'
              | 'west.lecture-hall-70'
              | 'west.digital-hall'
              | 'west.gym'
              | 'west.gym.gym-arena'
              | 'west.gym.gym-dojo'
              | 'west.circle-2'
              | 'west.circle-2.c2-102'
              | 'west.circle-2.c2-201'
              | 'north'
              | 'north.n1'
              | 'north.n1.n1-158'
              | 'north.n1.n1-parking'
              | 'north.n3'
              | 'north.n3.n3-lab'
              | 'north.lab1'
              | 'north.lab1.lab1-1f'
              | 'midorigaoka'
              | 'midorigaoka.mi6'
              | 'midorigaoka.mi6.mi6-302'
              | 'midorigaoka.mi6.mi6-303'
              | 'ishikawadai'
              | 'ishikawadai.i1'
              | 'ishikawadai.i1.i1-254'
              | 'ishikawadai.i1.i1-255'
              | 'ishikawadai.i1.i1-256'
              | 'ishikawadai.i1.i1-751'
              | 'ishikawadai.i7'
              | 'ishikawadai.i7.i7-mishima'
              | 'ishikawadai.i9'
              | 'ishikawadai.i9.i9-207'
              | 'ishikawadai.fs-ishikawadai'
              | 'ishikawadai.fs-ishikawadai.1'
              | 'ishikawadai.fs-ishikawadai.2'
              | 'ishikawadai.fs-ishikawadai.3'
              | 'ishikawadai.fs-ishikawadai.4'
              | 'ishikawadai.fs-ishikawadai.5'
              | 'ishikawadai.fs-ishikawadai.6'
              | 'ishikawadai.fs-ishikawadai.7';
            /** @enum {string} */
            type:
              | 'district'
              | 'building'
              | 'stage'
              | 'outdoor'
              | 'food_stall_area'
              | 'room'
              | 'food_stall_slot';
            name: string;
            displayName: string;
          }[];
        };
      };
      /** @description クエリパラメータが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        placeId:
          | 'east'
          | 'east.taki-plaza'
          | 'east.taki-plaza.tp-b1-event'
          | 'east.taki-plaza.tp-b2-event'
          | 'east.taki-plaza.tp-1'
          | 'east.centennial-hall'
          | 'east.centennial-hall.centennial-hall-1f'
          | 'east.taki-plaza-stage'
          | 'east.wood-deck-stage'
          | 'east.wood-deck'
          | 'east.outdoor-stage'
          | 'east.fs-east-icho'
          | 'east.fs-east-icho.1'
          | 'east.fs-east-icho.2'
          | 'east.fs-east-icho.3'
          | 'east.fs-east-icho.4'
          | 'east.fs-east-icho.5'
          | 'east.fs-east-icho.6'
          | 'east.fs-east-icho.7'
          | 'east.fs-east-icho.8'
          | 'east.fs-east-icho.9'
          | 'east.fs-east-icho.10'
          | 'east.fs-behind-taki-plaza'
          | 'east.fs-behind-taki-plaza.1'
          | 'east.fs-behind-taki-plaza.2'
          | 'east.fs-behind-taki-plaza.3'
          | 'east.fs-behind-taki-plaza.4'
          | 'east.fs-behind-taki-plaza.5'
          | 'east.fs-behind-taki-plaza.6'
          | 'east.fs-east-deck'
          | 'east.fs-east-deck.1'
          | 'east.fs-east-deck.2'
          | 'east.fs-east-deck.3'
          | 'east.fs-east-deck.4'
          | 'east.fs-east-deck.5'
          | 'east.fs-east-deck.6'
          | 'east.fs-east-deck.7'
          | 'east.fs-east-deck.8'
          | 'east.fs-east-deck.9'
          | 'east.fs-east-deck.10'
          | 'east.fs-east-deck.11'
          | 'main'
          | 'main.m'
          | 'main.m.m-b07'
          | 'main.m.m-b45'
          | 'main.m.m-b43'
          | 'main.m.m-101'
          | 'main.m.m-102'
          | 'main.m.m-107'
          | 'main.m.m-112'
          | 'main.m.m-119'
          | 'main.m.m-123'
          | 'main.m.m-134'
          | 'main.m.m-135'
          | 'main.m.m-143a'
          | 'main.m.m-143b'
          | 'main.m.m-155'
          | 'main.m.m-156'
          | 'main.m.m-157'
          | 'main.m.m-178'
          | 'main.m.m-278'
          | 'main.m.m-356'
          | 'main.m.m-b61'
          | 'main.m.m-213'
          | 'main.m.m-290'
          | 'main.m.m-124'
          | 'main.m.m-220'
          | 'main.m.m-225'
          | 'main.m.m-374'
          | 'main.mb'
          | 'main.mb.m-b101'
          | 'main.mb.m-b104'
          | 'main.mb.m-b107'
          | 'main.fs-honkan-main'
          | 'main.fs-honkan-main.1'
          | 'main.fs-honkan-main.2'
          | 'main.fs-honkan-main.3'
          | 'main.fs-honkan-main.4'
          | 'main.fs-honkan-main.5'
          | 'main.fs-honkan-main.6'
          | 'main.fs-honkan-main.7'
          | 'main.fs-honkan-main.8'
          | 'main.fs-honkan-main.9'
          | 'main.fs-honkan-main.10'
          | 'main.fs-honkan-main.11'
          | 'main.fs-honkan-main.12'
          | 'main.fs-honkan-main.13'
          | 'main.fs-honkan-main.14'
          | 'main.fs-honkan-west'
          | 'main.fs-honkan-west.1'
          | 'main.fs-honkan-west.2'
          | 'south'
          | 'south.s1'
          | 'south.s1.s1-101'
          | 'south.s2'
          | 'south.s2.s2-201'
          | 'south.s2.s2-202'
          | 'south.s2.s2-203'
          | 'south.s2.s2-204'
          | 'south.s2.s2-101'
          | 'south.s2.s2-109'
          | 'south.s2.mono'
          | 'south.s3'
          | 'south.s3.s3-206'
          | 'south.s3.s3-207'
          | 'south.s3.s3-215'
          | 'south.s3.s3-300'
          | 'south.s3.s3-310'
          | 'south.s3.s3-403'
          | 'south.s3.s3-413'
          | 'south.s3.s3-414'
          | 'south.s3.s3-505'
          | 'south.s3.s3-510'
          | 'south.s3.s3-601'
          | 'south.s3.s3-611'
          | 'south.s3.s3-906'
          | 'south.s3.s3-914'
          | 'south.s4'
          | 'south.s4.s4-201'
          | 'south.s4.s4-202'
          | 'south.s4.s4-203'
          | 'south.s7'
          | 'south.s7.s7-201'
          | 'south.s7.s7-202'
          | 'south.s7.s7-207'
          | 'south.s7.s7-512'
          | 'south.s7.s7-605'
          | 'south.s7.s7-701'
          | 'south.s7.s7-702'
          | 'south.s7.s7-703'
          | 'south.s7.s7-707'
          | 'south.s7.s7-804'
          | 'south.s7.s7-807'
          | 'south.s8'
          | 'south.s8.s8-101'
          | 'south.s8.s8-107'
          | 'south.s8.s8-501'
          | 'south.s8.s8-512'
          | 'south.s8.s8-516'
          | 'south.s8.s8-518'
          | 'south.s8.s8-520'
          | 'south.s8.s8-entrance'
          | 'south.sl'
          | 'south.sl.sl-101'
          | 'south.circle-1'
          | 'south.circle-1.c1-212'
          | 'south.lab2'
          | 'south.lab2.lab2-storage'
          | 'south.waste-station'
          | 'south.seven-front'
          | 'south.fs-south-east'
          | 'south.fs-south-east.1'
          | 'south.fs-south-east.2'
          | 'south.fs-south-east.3'
          | 'south.fs-south-east.4'
          | 'south.fs-south-east.5'
          | 'south.fs-south-east.6'
          | 'south.fs-south-east.7'
          | 'south.fs-south-east.8'
          | 'south.fs-south-east.9'
          | 'south.fs-south-east.10'
          | 'south.fs-south-east.11'
          | 'south.fs-south-east.12'
          | 'south.fs-south-east.13'
          | 'south.fs-south-east.14'
          | 'south.fs-south-east.15'
          | 'south.fs-south-east.16'
          | 'south.fs-south-east.17'
          | 'south.fs-south-east.18'
          | 'south.fs-south-east.19'
          | 'south.fs-south-east.20'
          | 'south.fs-south-east.21'
          | 'south.fs-south-east.22'
          | 'south.fs-south-east.23'
          | 'south.fs-south-east.24'
          | 'south.fs-south-west'
          | 'south.fs-south-west.1'
          | 'south.fs-south-west.2'
          | 'south.fs-south-west.3'
          | 'south.fs-south-west.4'
          | 'south.fs-south-west.5'
          | 'south.fs-south-west.6'
          | 'south.fs-south-west.7'
          | 'south.fs-south-west.8'
          | 'south.fs-south-west.9'
          | 'south.fs-south-west.10'
          | 'south.fs-south-west.11'
          | 'south.fs-south-west.12'
          | 'south.fs-south-west.13'
          | 'south.fs-south-west.14'
          | 'south.fs-south-west.15'
          | 'south.fs-south-west.16'
          | 'west'
          | 'west.w2'
          | 'west.w2.w2-401'
          | 'west.w2.w2-402'
          | 'west.w3'
          | 'west.w3.w3-201'
          | 'west.w3.w3-205'
          | 'west.w3.w3-207'
          | 'west.w3.w3-301'
          | 'west.w3.w3-305'
          | 'west.w3.w3-501'
          | 'west.w3.w3-707'
          | 'west.w3.w3-505'
          | 'west.w5'
          | 'west.w5.w5-104'
          | 'west.w5.w5-105'
          | 'west.w5.w5-106'
          | 'west.w5.w5-107'
          | 'west.w5.tsubame'
          | 'west.w8'
          | 'west.w8.w8-404'
          | 'west.w8.w8-407'
          | 'west.w8.w8-509'
          | 'west.w8.w8-601'
          | 'west.w8.w8-604'
          | 'west.w8.w8-609'
          | 'west.w8.w8-7rf'
          | 'west.w8.w8-901'
          | 'west.w8.w8-5ev'
          | 'west.w9'
          | 'west.w9.w9-201'
          | 'west.w9.w9-202'
          | 'west.w9.w9-321'
          | 'west.w9.w9-322'
          | 'west.w9.w9-323'
          | 'west.w9.w9-324'
          | 'west.w9.w9-325'
          | 'west.w9.w9-326'
          | 'west.w9.w9-327'
          | 'west.w9.w9-606a'
          | 'west.w9.w9-706'
          | 'west.w9.w9-707'
          | 'west.w9.w9-716'
          | 'west.w9.w9-733'
          | 'west.wl1'
          | 'west.wl1.wl1-201'
          | 'west.wl1.wl1-401'
          | 'west.wl2'
          | 'west.wl2.wl2-101'
          | 'west.wl2.wl2-201'
          | 'west.wl2.wl2-301'
          | 'west.wl2.wl2-401'
          | 'west.lecture-hall-70'
          | 'west.digital-hall'
          | 'west.gym'
          | 'west.gym.gym-arena'
          | 'west.gym.gym-dojo'
          | 'west.circle-2'
          | 'west.circle-2.c2-102'
          | 'west.circle-2.c2-201'
          | 'north'
          | 'north.n1'
          | 'north.n1.n1-158'
          | 'north.n1.n1-parking'
          | 'north.n3'
          | 'north.n3.n3-lab'
          | 'north.lab1'
          | 'north.lab1.lab1-1f'
          | 'midorigaoka'
          | 'midorigaoka.mi6'
          | 'midorigaoka.mi6.mi6-302'
          | 'midorigaoka.mi6.mi6-303'
          | 'ishikawadai'
          | 'ishikawadai.i1'
          | 'ishikawadai.i1.i1-254'
          | 'ishikawadai.i1.i1-255'
          | 'ishikawadai.i1.i1-256'
          | 'ishikawadai.i1.i1-751'
          | 'ishikawadai.i7'
          | 'ishikawadai.i7.i7-mishima'
          | 'ishikawadai.i9'
          | 'ishikawadai.i9.i9-207'
          | 'ishikawadai.fs-ishikawadai'
          | 'ishikawadai.fs-ishikawadai.1'
          | 'ishikawadai.fs-ishikawadai.2'
          | 'ishikawadai.fs-ishikawadai.3'
          | 'ishikawadai.fs-ishikawadai.4'
          | 'ishikawadai.fs-ishikawadai.5'
          | 'ishikawadai.fs-ishikawadai.6'
          | 'ishikawadai.fs-ishikawadai.7';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 指定した場所 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Place'];
        };
      };
      /** @description 指定したIDの場所が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  listProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 企画の一覧 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'][];
        };
      };
    };
  };
  getProjectDetails: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 指定した企画の詳細情報 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            additionalInfo?: string;
            menu?: {
              items: {
                name: string;
                price?: number;
                options: {
                  name: string;
                  price?: number;
                }[];
              }[];
              description: string;
            };
          };
        };
      };
      /** @description 指定した企画の詳細情報が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 指定した企画 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  getProjectIcon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 指定した企画のアイコン */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/png': string;
          'image/jpeg': string;
          'image/gif': string;
          'image/webp': string;
          'image/heic': string;
        };
      };
      /** @description クライアントが保持しているアイコンから未更新 */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 指定したアイコンが存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
      };
    };
    responses: {
      /** @description 登録した企画 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 同じ ID の企画が既に存在する */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  createProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectList'];
      };
    };
    responses: {
      /** @description 登録した企画 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectList'];
        };
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 同じ ID の企画が既に存在する */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
      };
    };
    responses: {
      /** @description 更新後の企画 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 削除に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  updateProjectDescription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectDescription'];
      };
    };
    responses: {
      /** @description 更新後の企画 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  updateProjectIcon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'image/png': string;
        'image/jpeg': string;
        'image/gif': string;
        'image/webp': string;
        'image/heic': string;
      };
    };
    responses: {
      /** @description 保存に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 画像データが空 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 画像が20 MBを超えている */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 画像形式がCloudflare Imagesの処理対象外 */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 画像の縦横比が1:1ではない */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  deleteProjectIcon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 削除に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  updateProjectMenu: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          items: {
            name: string;
            price?: number;
            options: {
              name: string;
              price?: number;
            }[];
          }[];
          description: string;
        };
      };
    };
    responses: {
      /** @description 保存に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  deleteProjectMenu: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 削除に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  updateProjectAdditionalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string;
      };
    };
    responses: {
      /** @description 保存に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description リクエストボディが不正 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  deleteProjectAdditionalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 削除に成功 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access の認証を通っていない */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
      /** @description 指定したIDの企画が存在しない */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
}
