type: object
description: 当日販売される商品情報（更新用）
properties:
  items:
    type: array
    description: 商品の一覧
    items:
      type: object
      properties:
        name:
          type: string
          description: 商品名
        price:
          type: number
          description: 値段
          nullable: true
        options:
          type: array
          description: トッピングやフレーバーなどのオプション
          items:
            type: object
            properties:
              name:
                type: string
                description: 商品名
              price:
                type: number
                description: 値段
                nullable: true
  description:
    type: string
    description: 商品全体の説明文
