import type {Metadata} from "next";
import {Noto_Sans_JP} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const notoSans = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(children);
  return (
    <html lang="ja">
    <body className={notoSans.className}>
    <Header/>
    {children}
    <Footer/>
    </body>
    </html>
  );
}
