import type {Metadata} from "next";
import {Noto_Sans_JP} from "next/font/google";
import "./globals.css";
import {Footer, Header, MobileNavigator} from "@koudaisai-portal/ui-generic";

const notoSans = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
    <body className={notoSans.className} id={"app"}>
        <Header header_type="admin" />
        <main className="content">
          <MobileNavigator header_type="admin"/>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
