name = "join"
compatibility_date = "2025-09-05"
preview_urls = true

[assets]
directory = "dist/client"

[observability]
enabled = true

[[routes]]
pattern = "join.koudaisai.jp"
custom_domain = true

[env.preview]
name = "join-preview"

[[env.preview.routes]]
pattern = "join-preview.koudaisai.jp"
custom_domain = true
