//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "form_responses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub response_id: Uuid,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub form_id: Uuid,
    pub respondent_id: Uuid,
    pub answers: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::forms::Entity",
        from = "Column::FormId",
        to = "super::forms::Column::FormId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Forms,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RespondentId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::forms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Forms.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
