//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "category")]
pub enum Category {
    #[sea_orm(string_value = "booth")]
    Booth,
    #[sea_orm(string_value = "general")]
    General,
    #[sea_orm(string_value = "stage")]
    Stage,
    #[sea_orm(string_value = "labo")]
    Labo,
}
