//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub first_name: String,
    pub last_name: String,
    pub m_address: String,
    pub password_hash: String,
    pub exhibitor_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exhibitors_root::Entity",
        from = "Column::ExhibitorId",
        to = "super::exhibitors_root::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExhibitorsRoot,
}

impl Related<super::exhibitors_root::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExhibitorsRoot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
