import {Noto_Sans_JP} from "next/font/google";
import {Inner} from "@/app/admin/inner";
import {Metadata} from "next";
import "../globals.css"

const notoSans = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex"
};


export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ja">
    <body className={notoSans.className} style={{margin: 0}} id={"app"}>
    <Inner>
      {children}
    </Inner>
    </body>
    </html>
  );
}

