import type {Metadata} from "next";
import { Noto_Sans_JP } from "next/font/google";
import "../globals.css";
import { Header } from "@koudaisai-portal/ui-generic";
import Footer from "@/components/Footer/Footer";

const notoSans = Noto_Sans_JP({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={notoSans.className}>
        <Header header_type="members"  />
        {children}
        <Footer />
      </body>
    </html>
  );
}
