import type {Metadata} from "next";
import { Noto_Sans_JP } from "next/font/google";
import "../globals.css";
import { Header, Footer, MobileNavigator } from "@koudaisai-portal/ui-generic";

const notoSans = Noto_Sans_JP({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={notoSans.className} id={"app"}>
        <Header header_type="members"  />
        <main className="content">
          {children}
          <MobileNavigator header_type="members"/>
        </main>
        <Footer />
      </body>
    </html>
  );
}
