name = "koudaisai-portal-portal"
compatibility_date = "2025-09-05"
preview_urls = true

[assets]
directory = "dist"

[observability]
enabled = true

[[routes]]
pattern = "portal.koudaisai.jp"
custom_domain = true