/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/exhibitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** すべての参加団体を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exhibition"][];
                    };
                };
            };
        };
        put?: never;
        /** 参加団体を追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewExhibition"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewExhibitionResponse"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 参加団体またはユーザーがすでに存在する */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exhibitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 参加団体を取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が属する参加団体のみ取得可能
         *     - **admin_oidcの場合**: 存在する全ての参加団体を取得可能
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 参加団体id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exhibition"];
                    };
                };
                /** @description 参加団体が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * 参加団体を編集
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が属する参加団体のみ編集可能
         *     - **admin_oidcの場合**: 存在する全ての参加団体を編集可能
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 参加団体id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditExhibition"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 参加団体が編集された */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 参加団体が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * アクセス可能なフォームをすべて取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: targetに基づいてアクセス可能なフォームを取得
         *     - **admin_oidcの場合**: 存在するフォームを全て取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FormRead"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** フォームを新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormCreate"];
                };
            };
            responses: {
                /** @description NoContent */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * フォームを取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: targetに基づいてアクセス可能なフォームな場合取得
         *     - **admin_oidcの場合**: 存在するフォームを全て取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォームID */
                    form_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FormRead"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** フォームを削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォームID */
                    form_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description フォームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** フォームを更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォームID */
                    form_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormUpdate"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * アクセス可能な資料をすべて取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が属する参加団体の属性に基づいてアクセス可能な資料を取得
         *     - **admin_oidcの場合**: 存在する資料を全て取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocument"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 資料を新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDocument"];
                };
            };
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocument"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 資料カテゴリと資料のマップを取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が属する参加団体の属性に基づいてアクセス可能な資料な場合取得
         *     - **admin_oidcの場合**: 存在する資料を全て取得可能
         */
        get: {
            parameters: {
                query?: {
                    /** @description 空のカテゴリも含めるかどうか。デフォルトは`false`。
                     *     `true`の場合、資料が存在しないカテゴリも含まれる。
                     *      */
                    include_empty_categories?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            category: components["schemas"]["ReadDocumentCategory"] | null;
                            documents: components["schemas"]["ReadDocument"][];
                        }[];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 資料を取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が属する参加団体の属性に基づいてアクセス可能な資料な場合取得
         *     - **admin_oidcの場合**: 存在する資料を全て取得可能
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 資料のID */
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocument"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** 資料を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description フォームID */
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description フォームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 資料を更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 資料のID */
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDocument"];
                };
            };
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocument"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/document-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 資料カテゴリをすべて取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocumentCategory"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 資料カテゴリを新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDocumentCategory"];
                };
            };
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocumentCategory"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document-categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 資料カテゴリを取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 資料カテゴリのID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocumentCategory"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** 資料カテゴリを削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description カテゴリID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description フォームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 資料カテゴリを更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 資料カテゴリのID */
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDocumentCategory"];
                };
            };
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadDocumentCategory"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ファイルのアップロードurlを取得 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        file_name: string;
                    };
                };
            };
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            presigned_url: string;
                            key: string;
                        };
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ファイルのダウンロードurlを取得 */
        get: {
            parameters: {
                query: {
                    key: string;
                    file_name: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            presigned_url?: string;
                        };
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザーを全て取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserRead"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー情報を取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: ユーザーが自身の所属する参加団体に所属している場合のみ取得可能
         *     - **admin_oidcの場合**: いかなるユーザー情報も取得可能
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserRead"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ユーザー情報を更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
            responses: {
                /** @description 更新成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/users/{user_id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** そのユーザー向けの通知と既読状況を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ユーザーID */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notification: components["schemas"]["NotificationRead"];
                            /** @description その通知が既読かどうかを示すフラグ
                             *     trueの場合、通知は既読であることを示す
                             *      */
                            is_read: boolean;
                        }[];
                    };
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全ての通知を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationRead"][];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** 通知を新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotificationCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 通知を取得
         * @description ### authの違いによる挙動の違い
         *     - **exhibitor_bearerの場合**: 自分が通知対象である場合通知を取得可能
         *     - **admin_oidcの場合**: 存在する通知を全て取得可能
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 通知id */
                    notification_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationRead"];
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** 通知を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 通知ID */
                    notification_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description フォームが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 通知を更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 通知ID */
                    notification_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotificationUpdate"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/util/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ページのメタデータを取得 */
        get: {
            parameters: {
                query: {
                    /** @description フォームID */
                    url: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The title of the page. */
                            title: string | null;
                            /** @description The description of the page. */
                            description: string | null;
                        };
                    };
                };
                /** @description 不正なrequest bodyの形式 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 資格情報が無効だった場合 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Exhibition: {
            /**
             * @description 参加団体id
             * @example T-001
             */
            id: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 最終更新日時
             */
            updated_at: string;
            /**
             * @description 参加団体名
             * @example U7374
             */
            exhibitor_name: string;
            /**
             * @description 企画名
             * @example 釈迦釈迦ポテト
             */
            exhibition_name?: string | null;
            /** @description アイコンのid */
            icon_id?: string | null;
            /** @description 企画概要 */
            description?: string | null;
            /**
             * @description 参加団体の種類
             * @example general
             * @enum {string}
             */
            type: "booth" | "general" | "stage" | "labo";
            /** @description 第一責任者, 第二責任者, 第三責任者 */
            representatives: string[];
        };
        User: {
            /**
             * Format: uuid
             * @description unique id
             */
            readonly id: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description 最終更新日時
             */
            readonly updated_at: string;
            /**
             * @description 名
             * @example Paul
             */
            first_name: string;
            /**
             * @description 姓
             * @example Johnson
             */
            last_name: string;
            /**
             * @description mアドレス(新旧どちらも含む)
             * @example johnson.p.5703@m.isct.ac.jp
             */
            m_address: string;
        };
        NewExhibition: {
            /**
             * @description 参加団体id
             * @example T-001
             */
            id: string;
            /**
             * @description 参加団体名
             * @example 釈迦釈迦ポテト
             */
            exhibitor_name: string;
            /**
             * @description 参加団体の種類
             * @example general
             * @enum {string}
             */
            type: "booth" | "general" | "stage" | "labo";
            /** @description 第一責任者, 第二責任者, 第三責任者 */
            representatives: components["schemas"]["User"][];
        };
        NewExhibitionResponse: {
            /** @description 第一責任者, 第二責任者, 第三責任者のactivation token */
            activation_tokens: unknown;
        };
        EditExhibition: {
            /**
             * @description 企画名
             * @example 釈迦釈迦ポテト
             */
            exhibition_name?: string;
            /** @description アイコンのid */
            icon_id?: string;
            /** @description 企画概要 */
            description?: string;
        };
        /** @description Target specifier for forms */
        TargetSpecifier: string & (("exhibitor/type/general" | "exhibitor/type/booth" | "exhibitor/type/stage" | "exhibitor/type/labo" | "user/nologin") | unknown);
        /** @description Generic form properties */
        FormReadGeneric: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /**
             * Format: date-time
             * @description Timestamp when the form was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Timestamp when the form was last updated
             */
            updated_at: string;
            /**
             * Format: uuid
             * @description User ID of the creator
             */
            created_by: string;
            /**
             * Format: uuid
             * @description User ID of the last updater
             */
            updated_by: string;
            /** @description Target specifiers for the form */
            targets: components["schemas"]["TargetSpecifier"][];
            /** @description Name of the form */
            form_name: string;
            /** @description Summary or description of the form */
            summary: string;
            /**
             * Format: date-time
             * @description Due date for the form submission
             */
            due_date: string | null;
        };
        /** @description フォームの一般情報 */
        Info: {
            /** @description 回答者に表示されるフォームのタイトル */
            title: string;
            /** @description 編集者に表示されるフォームのタイトル */
            document_title: string;
            /** @description フォームの説明 */
            description: string;
            /**
             * Format: datetime
             * @description フォームの回答期限
             */
            deadline?: string;
        };
        ItemGeneric: {
            /**
             * Format: uuid
             * @description アイテムのID
             */
            readonly item_id: string;
            /** @description 回答者に表示される項目のタイトル */
            title: string;
            /** @description 回答者に表示される項目の説明 */
            description: string;
        };
        QuestionGeneric: {
            /** @description 回答必須かどうか */
            required: boolean;
        };
        /** @description テキスト */
        QuestionText: {
            /** @description trueの場合複数行にわたるテキスト。falseの場合一行の回答。 */
            paragraph: boolean;
        };
        /** @description ラジオボタン */
        QuestionRadioButton: {
            /** @description 選択肢 */
            choices: string[];
        };
        /** @description チェックボックス */
        QuestionCheckBox: {
            /** @description 選択肢 */
            choices: string[];
        };
        /** @description フォームの質問 */
        Question: components["schemas"]["QuestionGeneric"] & {
            question_text?: components["schemas"]["QuestionText"];
            question_radio_button?: components["schemas"]["QuestionRadioButton"];
            question_check_box?: components["schemas"]["QuestionCheckBox"];
        };
        /** @description 一つの質問を含む項目 */
        ItemQuestion: {
            question: components["schemas"]["Question"];
        };
        /** @description 改ページ */
        ItemPageBreak: Record<string, never>;
        /** @description テキスト */
        ItemText: Record<string, never>;
        /** @description フォームの単一の項目 */
        Item: components["schemas"]["ItemGeneric"] & {
            item_question?: components["schemas"]["ItemQuestion"];
            item_page_break?: components["schemas"]["ItemPageBreak"];
            item_text?: components["schemas"]["ItemText"];
        };
        /** @description フォーム */
        Form: {
            /**
             * Format: uuid
             * @description フォームID
             */
            readonly form_id?: string;
            info: components["schemas"]["Info"];
            /** @description フォームのアイテムのリスト（質問、改ページ、テキストなど） */
            items: components["schemas"]["Item"][];
        };
        /** @description External form type */
        FormReadTypeExternal: {
            /**
             * Format: uri
             * @description URL of the external form
             */
            form_url: string;
        };
        /** @description Form read request */
        FormRead: (components["schemas"]["FormReadGeneric"] & {
            type_builtin: components["schemas"]["Form"];
        }) | (components["schemas"]["FormReadGeneric"] & {
            type_external: components["schemas"]["FormReadTypeExternal"];
        });
        /** @description Generic form properties */
        FormCreateGeneric: {
            /** @description Target specifiers for the form */
            targets: components["schemas"]["TargetSpecifier"][];
            /** @description Name of the form */
            form_name: string;
            /** @description Summary or description of the form */
            summary: string;
            /**
             * Format: date-time
             * @description Due date for the form submission
             */
            due_date: string | null;
        };
        /** @description External form type */
        FormCreateTypeExternal: {
            /**
             * Format: uri
             * @description URL of the external form
             */
            form_url: string;
        };
        /** @description Form creation request */
        FormCreate: components["schemas"]["FormCreateGeneric"] & ({
            type_builtin: components["schemas"]["Form"];
        } | {
            type_external: components["schemas"]["FormCreateTypeExternal"];
        });
        /** @description Generic form properties */
        FormUpdateGeneric: {
            /** @description Target specifiers for the form */
            targets?: components["schemas"]["TargetSpecifier"][];
            /** @description Name of the form */
            form_name?: string;
            /** @description Summary or description of the form */
            summary?: string;
            /**
             * Format: date-time
             * @description Due date for the form submission
             */
            due_date?: string | null;
        };
        /** @description External form type */
        FormUpdateTypeExternal: {
            /**
             * Format: uri
             * @description URL of the external form
             */
            form_url?: string;
        };
        FormUpdate: (components["schemas"]["FormUpdateGeneric"] & {
            type_builtin: components["schemas"]["Form"];
        }) | (components["schemas"]["FormUpdateGeneric"] & {
            type_external: components["schemas"]["FormUpdateTypeExternal"];
        }) | components["schemas"]["FormUpdateGeneric"];
        ReadDocumentGeneric: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            updated_by: string;
            title: string;
            /** Format: uuid */
            category: string | null;
            required_one_of_scopes: string[];
        };
        /** @description マークダウン形式の資料 */
        ReadDocumentFormatMarkdown: {
            content: string;
        };
        /** @description pdf形式の資料 */
        ReadDocumentFormatPdf: {
            file_key: string;
            file_name: string;
        };
        /** @description 任意形式の資料 */
        ReadDocumentFormatMisc: {
            file_key: string;
            file_name: string;
        };
        ReadDocument: components["schemas"]["ReadDocumentGeneric"] & {
            format_markdown?: components["schemas"]["ReadDocumentFormatMarkdown"];
            format_pdf?: components["schemas"]["ReadDocumentFormatPdf"];
            format_misc?: components["schemas"]["ReadDocumentFormatMisc"];
        };
        CreateDocumentGeneric: {
            title: string;
            /** Format: uuid */
            category: string | null;
            required_one_of_scopes: string[];
        };
        /** @description マークダウン形式の資料 */
        CreateDocumentFormatMarkdown: {
            content: string;
        };
        /** @description pdf形式の資料 */
        CreateDocumentFormatPdf: {
            file_key: string;
            file_name: string;
        };
        /** @description 任意形式の資料 */
        CreateDocumentFormatMisc: {
            file_key: string;
            file_name: string;
        };
        CreateDocument: components["schemas"]["CreateDocumentGeneric"] & {
            format_markdown?: components["schemas"]["CreateDocumentFormatMarkdown"];
            format_pdf?: components["schemas"]["CreateDocumentFormatPdf"];
            format_misc?: components["schemas"]["CreateDocumentFormatMisc"];
        };
        /** @description 資料のカテゴリー */
        ReadDocumentCategory: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            title: string;
            emoji: string | null;
        };
        UpdateDocumentGeneric: {
            title?: string;
            /** Format: uuid */
            category?: string | null;
            required_one_of_scopes?: string[];
        };
        /** @description マークダウン形式の資料 */
        UpdateDocumentFormatMarkdown: {
            content: string;
        };
        /** @description pdf形式の資料 */
        UpdateDocumentFormatPdf: {
            file_key: string;
            file_name: string;
        };
        /** @description 任意形式の資料 */
        UpdateDocumentFormatMisc: {
            file_key: string;
            file_name: string;
        };
        UpdateDocument: (components["schemas"]["UpdateDocumentGeneric"] & {
            format_markdown?: components["schemas"]["UpdateDocumentFormatMarkdown"];
        }) | (components["schemas"]["UpdateDocumentGeneric"] & {
            format_pdf?: components["schemas"]["UpdateDocumentFormatPdf"];
        }) | (components["schemas"]["UpdateDocumentGeneric"] & {
            format_misc?: components["schemas"]["UpdateDocumentFormatMisc"];
        }) | components["schemas"]["UpdateDocumentGeneric"];
        /** @description 資料のカテゴリー */
        CreateDocumentCategory: {
            title: string;
            emoji: string | null;
        };
        /** @description 資料のカテゴリー */
        UpdateDocumentCategory: {
            title?: string;
            emoji?: string | null;
        };
        UserRead: {
            /**
             * Format: uuid
             * @description unique id
             */
            readonly id: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description 最終更新日時
             */
            readonly updated_at: string;
            /**
             * @description 名
             * @example Paul
             */
            first_name: string;
            /**
             * @description 姓
             * @example Johnson
             */
            last_name: string;
            /**
             * @description mアドレス(新旧どちらも含む)
             * @example johnson.p.5703@m.isct.ac.jp
             */
            m_address: string;
            /**
             * @description 参加団体id
             * @example T-001
             */
            exhibition_id: string;
        };
        UserUpdate: {
            /**
             * @description 名
             * @example Paul
             */
            first_name?: string;
            /**
             * @description 姓
             * @example Johnson
             */
            last_name?: string;
            /**
             * @description mアドレス(新旧どちらも含む)
             * @example johnson.p.5703@m.isct.ac.jp
             */
            m_address?: string;
        };
        NotificationReadGeneric: {
            /**
             * Format: uuid
             * @description 通知ID
             */
            id: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 最終更新日時
             */
            updated_at: string;
            /**
             * Format: uuid
             * @description 作成者のユーザーID
             */
            created_by: string;
            /**
             * Format: uuid
             * @description 最終更新者のユーザーID
             */
            updated_by: string;
            /** @description 通知のタイトル */
            title: string;
            /** @description 通知の対象を含む配列
             *     - `exhibitor/type/general` - 一般企画責任者
             *     - `exhibitor/type/booth` - 模擬店企画責任者
             *     - `exhibitor/type/stage` - ステージ企画責任者
             *     - `exhibitor/type/labo` - 研究室企画責任者
             *     - `user/id/${user_id}` - 特定のユーザー
             *     - `user/nologin` - ログインしていないユーザー
             *      */
            target: string[];
        };
        /** @description マークダウンタイプの通知 */
        NotificationReadTypeMarkdown: {
            content: string;
        };
        NotificationRead: components["schemas"]["NotificationReadGeneric"] & {
            type_markdown: components["schemas"]["NotificationReadTypeMarkdown"];
        };
        NotificationCreateGeneric: {
            /** @description 通知のタイトル */
            title: string;
            /** @description 通知の対象を含む配列
             *     - `exhibitor/type/general` - 一般企画責任者
             *     - `exhibitor/type/booth` - 模擬店企画責任者
             *     - `exhibitor/type/stage` - ステージ企画責任者
             *     - `exhibitor/type/labo` - 研究室企画責任者
             *     - `user/id/${user_id}` - 特定のユーザー
             *     - `user/nologin` - ログインしていないユーザー
             *      */
            target: string[];
        };
        /** @description マークダウンタイプの通知 */
        NotificationCreateTypeMarkdown: {
            content: string;
        };
        NotificationCreate: components["schemas"]["NotificationCreateGeneric"] & {
            type_markdown: components["schemas"]["NotificationCreateTypeMarkdown"];
        };
        NotificationUpdateGeneric: {
            /** @description 通知のタイトル */
            title?: string;
            /** @description 通知の対象を含む配列
             *     - `exhibitor/type/general` - 一般企画責任者
             *     - `exhibitor/type/booth` - 模擬店企画責任者
             *     - `exhibitor/type/stage` - ステージ企画責任者
             *     - `exhibitor/type/labo` - 研究室企画責任者
             *     - `user/id/${user_id}` - 特定のユーザー
             *     - `user/nologin` - ログインしていないユーザー
             *      */
            target?: string[];
        };
        /** @description マークダウンタイプの通知 */
        NotificationUpdateTypeMarkdown: {
            content?: string;
        };
        NotificationUpdate: (components["schemas"]["NotificationUpdateGeneric"] & {
            type_markdown: components["schemas"]["NotificationUpdateTypeMarkdown"];
        }) | components["schemas"]["NotificationUpdateGeneric"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
