name: Build and Publish Docker Image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/jizi-isct/koudaisai-portal-backend

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Decide tags
        id: tags
        run: |
          TAGS="preview"
          if [[ "${{ github.event.release.prerelease }}" == "false" ]]; then
            TAGS="$TAGS latest"
          fi
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"
      - name: Build image once and retag
        run: |
          VERSION="${{ github.ref_name }}"
          docker build -t $IMAGE_NAME:$VERSION .
          for tag in $TAGS; do
            docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$tag
          done
      - name: Push all tags
        run: |
          VERSION="${{ github.ref_name }}"
          docker push $IMAGE_NAME:$VERSION
          for tag in $TAGS; do
            docker push $IMAGE_NAME:$tag
          done
