//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "approval_request_type_edit_exhibition_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::approval_request::Entity",
        from = "Column::Id",
        to = "super::approval_request::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApprovalRequest,
}

impl Related<super::approval_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
