//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::DocumentFormat;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "document")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub created_by: Uuid,
    pub updated_by: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub format: DocumentFormat,
    pub category: Option<Uuid>,
    pub required_one_of_scopes: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::document_category::Entity",
        from = "Column::Category",
        to = "super::document_category::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DocumentCategory,
    #[sea_orm(has_one = "super::document_format_markdown::Entity")]
    DocumentFormatMarkdown,
    #[sea_orm(has_one = "super::document_format_misc::Entity")]
    DocumentFormatMisc,
    #[sea_orm(has_one = "super::document_format_pdf::Entity")]
    DocumentFormatPdf,
}

impl Related<super::document_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentCategory.def()
    }
}

impl Related<super::document_format_markdown::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentFormatMarkdown.def()
    }
}

impl Related<super::document_format_misc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentFormatMisc.def()
    }
}

impl Related<super::document_format_pdf::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentFormatPdf.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
