//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::ExhibitionType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exhibitors_root")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub exhibitor_name: String,
    pub r#type: ExhibitionType,
    #[sea_orm(column_type = "Text", nullable)]
    pub exhibition_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub representative1: Option<Uuid>,
    pub representative2: Option<Uuid>,
    pub representative3: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::exhibitors_category_booth::Entity")]
    ExhibitorsCategoryBooth,
    #[sea_orm(has_one = "super::exhibitors_category_general::Entity")]
    ExhibitorsCategoryGeneral,
    #[sea_orm(has_one = "super::exhibitors_category_labo::Entity")]
    ExhibitorsCategoryLabo,
    #[sea_orm(has_one = "super::exhibitors_category_stage::Entity")]
    ExhibitorsCategoryStage,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative1",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative2",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative3",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::exhibitors_category_booth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExhibitorsCategoryBooth.def()
    }
}

impl Related<super::exhibitors_category_general::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExhibitorsCategoryGeneral.def()
    }
}

impl Related<super::exhibitors_category_labo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExhibitorsCategoryLabo.def()
    }
}

impl Related<super::exhibitors_category_stage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExhibitorsCategoryStage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
