//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "form_type_builtin")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub form_id: Uuid,
    pub info: Json,
    pub items: Json,
    pub access_control_roles: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form::Entity",
        from = "Column::FormId",
        to = "super::form::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Form,
    #[sea_orm(has_many = "super::form_type_builtin_response::Entity")]
    FormTypeBuiltinResponse,
}

impl Related<super::form::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Form.def()
    }
}

impl Related<super::form_type_builtin_response::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormTypeBuiltinResponse.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
