//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::FormType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "form")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub targets: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub form_name: String,
    pub r#type: FormType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::form_type_builtin::Entity")]
    FormTypeBuiltin,
    #[sea_orm(has_one = "super::form_type_external::Entity")]
    FormTypeExternal,
}

impl Related<super::form_type_builtin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormTypeBuiltin.def()
    }
}

impl Related<super::form_type_external::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormTypeExternal.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
