//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::GroupType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub exhibitor_name: String,
    pub r#type: GroupType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::group_plan::Entity")]
    GroupPlan,
    #[sea_orm(has_one = "super::group_press::Entity")]
    GroupPress,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::group_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlan.def()
    }
}

impl Related<super::group_press::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPress.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
