//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_plan_stage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub representative1: Uuid,
    pub representative2: Uuid,
    pub representative3: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_plan::Entity",
        from = "Column::Id",
        to = "super::group_plan::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GroupPlan,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative1",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative2",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative3",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::group_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlan.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
