//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::PlanType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_plan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub r#type: PlanType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group::Entity",
        from = "Column::Id",
        to = "super::group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Group,
    #[sea_orm(has_one = "super::group_plan_booth::Entity")]
    GroupPlanBooth,
    #[sea_orm(has_one = "super::group_plan_general::Entity")]
    GroupPlanGeneral,
    #[sea_orm(has_one = "super::group_plan_labo::Entity")]
    GroupPlanLabo,
    #[sea_orm(has_one = "super::group_plan_stage::Entity")]
    GroupPlanStage,
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Group.def()
    }
}

impl Related<super::group_plan_booth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlanBooth.def()
    }
}

impl Related<super::group_plan_general::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlanGeneral.def()
    }
}

impl Related<super::group_plan_labo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlanLabo.def()
    }
}

impl Related<super::group_plan_stage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlanStage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
