//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_plan_labo")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub representative: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_plan::Entity",
        from = "Column::Id",
        to = "super::group_plan::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GroupPlan,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representative",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::group_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPlan.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
