//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::NotificationType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub target: Vec<String>,
    pub r#type: NotificationType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::notification_type_approval_request::Entity")]
    NotificationTypeApprovalRequest,
    #[sea_orm(has_one = "super::notification_type_markdown::Entity")]
    NotificationTypeMarkdown,
    #[sea_orm(has_many = "super::read_notifications::Entity")]
    ReadNotifications,
}

impl Related<super::notification_type_approval_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTypeApprovalRequest.def()
    }
}

impl Related<super::notification_type_markdown::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTypeMarkdown.def()
    }
}

impl Related<super::read_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReadNotifications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
