//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "approval_request_status"
)]
pub enum ApprovalRequestStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "closed")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "approval_request_type"
)]
pub enum ApprovalRequestType {
    #[sea_orm(string_value = "type_edit_exhibition_info")]
    TypeEditExhibitionInfo,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "document_format")]
pub enum DocumentFormat {
    #[sea_orm(string_value = "PDF")]
    Pdf,
    #[sea_orm(string_value = "MARKDOWN")]
    Markdown,
    #[sea_orm(string_value = "misc")]
    Misc,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "form_type")]
pub enum FormType {
    #[sea_orm(string_value = "BUILTIN")]
    Builtin,
    #[sea_orm(string_value = "EXTERNAL")]
    External,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "group_type")]
pub enum GroupType {
    #[sea_orm(string_value = "plan")]
    Plan,
    #[sea_orm(string_value = "press")]
    Press,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "notification_type")]
pub enum NotificationType {
    #[sea_orm(string_value = "MARKDOWN")]
    Markdown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "plan_type")]
pub enum PlanType {
    #[sea_orm(string_value = "BOOTH")]
    Booth,
    #[sea_orm(string_value = "GENERAL")]
    General,
    #[sea_orm(string_value = "STAGE")]
    Stage,
    #[sea_orm(string_value = "LABO")]
    Labo,
}
